# Generated by Django 5.1.7 on 2025-03-29 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_confirmacionrecepcion_observaciones_and_more'),
        ('notificaciones', '0002_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='bodega.salidaproducto'),
        ),
    ]
