# Generated by Django 5.1.6 on 2025-03-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='garantia_meses',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
    ]
