# Generated by Django 5.1.7 on 2025-03-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseno',
            options={'verbose_name': 'Diseño', 'verbose_name_plural': 'Diseños'},
        ),
    ]
