# Generated by Django 5.2.1 on 2025-06-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_alter_diseno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='diseno',
            field=models.ManyToManyField(blank=True, null=True, related_name='productos', to='Producto.diseno'),
        ),
    ]
