# Generated by Django 5.1.7 on 2025-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_alter_producto_diseno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='diseno',
            field=models.ManyToManyField(blank=True, related_name='productos', to='Producto.diseno'),
        ),
    ]
