<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-07-10 16:49
=======
# Generated by Django 5.2.1 on 2025-06-27 19:00
>>>>>>> 643adfc824046c69f17e7c2d9a2feb0e565088a1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_alter_producto_diseno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='diseno',
            field=models.ManyToManyField(blank=True, related_name='productos', to='Producto.diseno'),
        ),
    ]
