# Generated by Django 5.1.7 on 2025-07-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_alter_producto_diseno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseno',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenDiseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_diseños')),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Producto.diseno')),
            ],
        ),
    ]
