# Generated by Django 5.1.7 on 2025-09-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_remove_diseno_imagen_imagendiseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='costo',
            field=models.FloatField(default=0.0, help_text='Costo de adquisición del producto'),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='precio_sugerido',
            field=models.FloatField(default=0.0, help_text='Precio sugerido de venta'),
        ),
    ]
