# Generated by Django 5.1.6 on 2025-03-15 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuentas', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.cliente')),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.facturaventa')),
                ('LocalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.local')),
            ],
        ),
    ]
