# Generated by Django 5.2.1 on 2025-07-11 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_remove_diseno_imagen_imagendiseno'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='Factura',
            new_name='FacturaID',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='ClienteID',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('vr_unidad', models.FloatField()),
                ('vr_total', models.FloatField()),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('productoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
                ('ventaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.ventas')),
            ],
        ),
    ]
