# Generated by Django 5.2.4 on 2025-07-18 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_remove_diseno_imagen_imagendiseno'),
        ('Ventas', '0002_rename_factura_ventas_facturaid_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='DetalleVentas',
        ),
        migrations.AddField(
            model_name='ventas',
            name='user_responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
            preserve_default=False,
        ),
    ]
