# Generated by Django 5.2.4 on 2025-07-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_remove_diseno_imagen_imagendiseno'),
        ('Ventas', '0003_rename_item_detalleventas_ventas_user_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventas',
            name='productoID',
        ),
        migrations.AddField(
            model_name='detalleventas',
            name='varianteID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Producto.productovariante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='ventaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Ventas.ventas'),
        ),
    ]
