# Generated by Django 5.2.4 on 2025-07-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_remove_detalleventas_productoid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='user_responsable',
            new_name='vendedor',
        ),
    ]
