# Generated by Django 5.2.4 on 2025-07-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_rename_user_responsable_ventas_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='FacturaID',
            new_name='factura',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='LocalID',
            new_name='local',
        ),
    ]
