# Generated by Django 5.2.4 on 2025-07-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_rename_facturaid_ventas_factura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventas',
            old_name='varianteID',
            new_name='variante',
        ),
        migrations.RenameField(
            model_name='detalleventas',
            old_name='ventaID',
            new_name='venta',
        ),
    ]
