# Generated by Django 5.2.4 on 2025-07-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_rename_varianteid_detalleventas_variante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='factura',
        ),
    ]
