# Generated by Django 5.1.7 on 2025-08-26 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0019_alter_facturacompra_estado'),
        ('Ventas', '0009_ventas_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='Cuentas.facturaventa'),
        ),
    ]
