# Generated by Django 5.1.7 on 2025-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0010_ventas_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta de Crédito/Débito')], max_length=20, null=True),
        ),
    ]
