# Generated by Django 5.1.7 on 2025-08-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0011_ventas_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventas',
            name='descuento_item',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detalleventas',
            name='ganancia_item',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='detalleventas',
            name='iva_item',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cambio',
            field=models.FloatField(default=0, help_text='Cambio que se le debe dar al cliente'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='codigo',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='descuento_porcentaje',
            field=models.FloatField(default=0, help_text='Porcentaje de descuento aplicado a la venta'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='descuento_total',
            field=models.FloatField(default=0, help_text='Valor absoluto de descuento aplicado'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='ganancia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventas',
            name='iva',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventas',
            name='tiene_devolucion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta de Crédito/Débito')], default='Efectivo', max_length=20),
        ),
    ]
