# Generated by Django 5.1.7 on 2025-09-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0012_detalleventas_descuento_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cambio',
        ),
    ]
