# Generated by Django 5.1.7 on 2025-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0013_remove_ventas_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cambio',
            field=models.FloatField(default=0, help_text='Cambio que se le debe dar al cliente'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
