# Generated by Django 5.1.7 on 2025-03-22 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AportesParafiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sena', models.FloatField()),
                ('icbf', models.FloatField()),
                ('caja_compensacion', models.FloatField()),
                ('aporte_salud', models.FloatField()),
            ],
            options={
                'verbose_name': 'Aporte Parafiscal',
                'verbose_name_plural': 'Aportes Parafiscales',
            },
        ),
        migrations.CreateModel(
            name='ARL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'ARL',
                'verbose_name_plural': 'ARL',
            },
        ),
        migrations.CreateModel(
            name='CajaCompensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Caja de Compensación',
                'verbose_name_plural': 'Cajas de Compensación',
            },
        ),
        migrations.CreateModel(
            name='Deducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salud', models.FloatField()),
                ('pension', models.FloatField()),
                ('fondo', models.FloatField()),
                ('retencion', models.FloatField()),
                ('otros', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Devengado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auxilio_transporte', models.FloatField()),
                ('exonerado_aportes', models.FloatField()),
                ('dias_liquidados', models.IntegerField()),
                ('horas_extras', models.IntegerField()),
                ('recargos_nocturnos', models.IntegerField()),
                ('recargos_dominical', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'EPS',
                'verbose_name_plural': 'EPS',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_pago', models.DateField()),
                ('fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('neto_pagado', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Pensión',
                'verbose_name_plural': 'Pensiones',
            },
        ),
        migrations.CreateModel(
            name='Provisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension', models.FloatField()),
                ('salud', models.FloatField()),
                ('riesgo_laboral', models.FloatField()),
                ('sena', models.FloatField()),
                ('icbf', models.FloatField()),
                ('caja_compensacion', models.FloatField()),
                ('prima', models.FloatField()),
                ('cesantias', models.FloatField()),
                ('interes_cesantias', models.FloatField()),
                ('vacaciones', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name': 'Provision',
                'verbose_name_plural': 'Provisiones',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario', models.FloatField()),
                ('arl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.arl')),
                ('caja_compensacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.cajacompensacion')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa_usuario', to='empresas.empresa')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Local_relacionado', to='locales.local')),
            ],
        ),
    ]
