# Generated by Django 5.1.6 on 2025-03-15 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='aportesparafiscal',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.contrato'),
        ),
        migrations.AddField(
            model_name='deducciones',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.contrato'),
        ),
        migrations.AddField(
            model_name='devengado',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.eps'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='aportes_parafiscal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nomina.aportesparafiscal'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.contrato'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='deducciones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nomina.deducciones'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='devengado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nomina.devengado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomina.pension'),
        ),
        migrations.AddField(
            model_name='provisiones',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='provisiones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nomina.provisiones'),
        ),
    ]
