# Generated by Django 5.1.6 on 2025-03-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_local_empresa'),
        ('nomina', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa_usuario', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Local_relacionado', to='empresas.local'),
        ),
    ]
