# Generated by Django 5.1.7 on 2025-03-20 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
        ('nomina', '0003_alter_contrato_empresa_alter_contrato_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Local_relacionado', to='locales.local'),
        ),
    ]
