# Generated by Django 5.1.7 on 2025-04-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_alter_contrato_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='periodo_pago',
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_fin',
            field=models.DateField(blank=True, default='2025-01-31', null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='fecha_inicio',
            field=models.DateField(blank=True, default='2025-01-01', null=True),
        ),
    ]
