# Generated by Django 5.1.7 on 2025-04-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0005_remove_nomina_periodo_pago_nomina_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='fecha_fin',
            field=models.DateField(blank=True, default='2025-01-31'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='fecha_inicio',
            field=models.DateField(blank=True, default='2025-01-01'),
        ),
    ]
