# Generated by Django 5.1.7 on 2025-04-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_alter_nomina_fecha_fin_alter_nomina_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='arl',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
        migrations.AddField(
            model_name='cajacompensacion',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
        migrations.AddField(
            model_name='eps',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
        migrations.AddField(
            model_name='pension',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
