# Generated by Django 5.1.7 on 2025-06-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_arl_estado_cajacompensacion_estado_eps_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arl',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arl',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
