# Generated by Django 5.2.1 on 2025-06-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_arl_estado_cajacompensacion_estado_eps_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportesparafiscal',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
