# Generated by Django 5.1.7 on 2025-06-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_alter_arl_correo_alter_arl_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arl',
            name='correo',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='arl',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
