# Generated by Django 5.2.1 on 2025-07-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_alter_arl_correo_alter_arl_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportesparafiscal',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
