# Generated by Django 5.2.4 on 2025-07-24 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0011_remove_aportesparafiscal_caja_compensacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 24)),
        ),
    ]
