# Generated by Django 5.2.4 on 2025-07-28 20:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0012_alter_nomina_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devengado',
            old_name='exonerado_aportes',
            new_name='comisiones',
        ),
        migrations.RemoveField(
            model_name='aportesparafiscal',
            name='aporte_salud',
        ),
        migrations.RemoveField(
            model_name='provisiones',
            name='caja_compensacion',
        ),
        migrations.RemoveField(
            model_name='provisiones',
            name='icbf',
        ),
        migrations.RemoveField(
            model_name='provisiones',
            name='sena',
        ),
        migrations.AddField(
            model_name='contrato',
            name='ibc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devengado',
            name='total_horas_extras_diurna',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='devengado',
            name='total_horas_extras_diurna_dominical',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='devengado',
            name='total_horas_extras_nocturna',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='devengado',
            name='total_horas_extras_nocturna_dominical',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='devengado',
            name='total_recargos_dominical',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='devengado',
            name='total_recargos_nocturnos',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='devengado',
            name='total_recargos_nocturnos_dominical',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='provisiones',
            name='aportes_parafiscal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nomina.aportesparafiscal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provisiones',
            name='nivel_riesgo',
            field=models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 44'), ('5', 'Nivel 5')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='aportesparafiscal',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='salario',
            field=models.FloatField(default=1423500),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 28)),
        ),
        migrations.AlterField(
            model_name='provisiones',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.contrato'),
        ),
    ]
