# Generated by Django 5.2.4 on 2025-07-28 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0013_rename_exonerado_aportes_devengado_comisiones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='aportesparafiscal',
            name='aporte_salud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nomina',
            name='periodo_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='neto_pagado',
            field=models.FloatField(default=0),
        ),
    ]
