# Generated by Django 5.1.7 on 2025-08-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0014_remove_nomina_fecha_fin_remove_nomina_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deducciones',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devengado',
            name='ibc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='devengado',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
