# Generated by Django 5.1.6 on 2025-03-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pieza', models.CharField(choices=[('Delantero', 'Delantero'), ('Posterior', 'Posterior'), ('Mangas', 'Mangas'), ('Cuellos', 'Cuellos'), ('Bolsillos', 'Bolsillos')], default='Delantero', max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CorteTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largo_utilizado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capas_cortadas', models.PositiveIntegerField()),
                ('colas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('faltante_tela', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rendimiento_rollo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_corte', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('total_unidades', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Orden Produccion',
                'verbose_name_plural': 'Orden Produccion',
            },
        ),
        migrations.CreateModel(
            name='RolloTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largo_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largo_restante', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto'), ('Agotado', 'Agotado')], default='Completo', max_length=50)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TallaCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=2)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
