# Generated by Django 5.1.7 on 2025-03-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollotela',
            name='kilos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rollotela',
            name='metros_solicitados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
