# Generated by Django 5.1.7 on 2025-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='identificacion',
            field=models.IntegerField(default='0', unique=True),
        ),
    ]
