# Generated by Django 5.2.1 on 2025-07-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_cliente_identificacion'),
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
