# Generated by Django 5.2.1 on 2025-07-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_alter_facturacompra_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='monto_total',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='monto_total',
            field=models.FloatField(blank=True),
        ),
    ]
