# Generated by Django 5.2.1 on 2025-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0004_cliente_direccion_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
