# Generated by Django 5.1.7 on 2025-07-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0006_alter_cliente_direccion_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='saldo_pendiente',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='saldo_pendiente',
            field=models.FloatField(null=True),
        ),
    ]
