# Generated by Django 5.2.4 on 2025-07-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0007_alter_facturacompra_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.IntegerField(unique=True),
        ),
    ]
