# Generated by Django 5.2.4 on 2025-07-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0008_alter_cliente_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('CC', 'Cedula Ciudadania'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
