# Generated by Django 5.2.4 on 2025-07-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0009_cliente_tipo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula Ciudadania'), ('NIT', 'Número Identificación Tributaria'), ('PAS', 'Pasaporte')], max_length=50),
        ),
    ]
