# Generated by Django 5.2.4 on 2025-07-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0010_alter_cliente_tipo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cedula Ciudadania'), ('NIT', 'Número Identificación Tributaria'), ('PAS', 'Pasaporte')], default='Cedula Ciudadania', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta de Crédito/Débito')], default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagorecibido',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta de Crédito/Débito')], default='Efectivo', max_length=50),
        ),
    ]
