# Generated by Django 5.2.4 on 2025-07-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0012_alter_cliente_tipo_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacompra',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='facturaventa',
            name='fecha_vencimiento',
        ),
    ]
