# Generated by Django 5.2.4 on 2025-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0013_remove_facturacompra_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='fecha_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
