# Generated by Django 5.2.4 on 2025-07-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0014_facturacompra_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='estado',
            field=models.CharField(choices=[('Completo', 'Saldado'), ('Incompleto', 'Pendiente'), ('Agotado', 'Cancelado')], default='Incompleto', max_length=50),
        ),
    ]
