# Generated by Django 5.2.4 on 2025-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0015_facturacompra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='estado',
            field=models.CharField(choices=[('Saldado', 'Saldado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], max_length=50),
        ),
    ]
