# Generated by Django 5.2.4 on 2025-07-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0016_alter_facturacompra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='estado',
            field=models.CharField(choices=[('Saldado', 'Saldado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='saldo_pendiente',
            field=models.FloatField(default=0),
        ),
    ]
