# Generated by Django 5.2.1 on 2025-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0017_alter_facturacompra_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='saldo_pendiente',
            field=models.FloatField(null=True),
        ),
    ]
