# Generated by Django 5.2.1 on 2025-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0018_alter_facturacompra_saldo_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='estado',
            field=models.CharField(choices=[('Saldado', 'Saldado'), ('Pendiente', 'Pendiente'), ('Vencido', 'Vencido')], default='Pendiente', max_length=50),
        ),
    ]
