# Generated by Django 5.1.7 on 2025-09-01 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0019_alter_facturacompra_estado'),
        ('Ventas', '0013_remove_ventas_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagorecibido',
            name='factura',
        ),
        migrations.AddField(
            model_name='pagorecibido',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Ventas.ventas'),
        ),
    ]
