# Generated by Django 5.1.6 on 2025-03-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_local_empresa'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Area_relacionada', to='empresas.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Cargo', to='usuarios.cargo'),
            preserve_default=False,
        ),
    ]
