# Generated by Django 5.1.6 on 2025-03-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresos_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Salidas_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Activo', 'Active'), ('Inactivo', 'Inactive')], default='Activo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uso_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cantidad', models.IntegerField()),
                ('Observaciones_Destino', models.CharField(max_length=100)),
            ],
        ),
    ]
