# Generated by Django 5.1.7 on 2025-03-22 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
        ('bodega', '0001_initial'),
        ('locales', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionrecepcion',
            name='user_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='entregacorte',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Producto.productovariante'),
        ),
        migrations.AddField(
            model_name='entregacorte',
            name='user_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='ingresoinsumo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='ingresoinsumo',
            name='user_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='ingresoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='bodega.insumo'),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.inventariolocal'),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='Producto.productovariante'),
        ),
        migrations.AddField(
            model_name='salidaproducto',
            name='user_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='confirmacionrecepcion',
            name='salida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion', to='bodega.salidaproducto'),
        ),
        migrations.AddField(
            model_name='stock',
            name='producto_variante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodega_stock', to='Producto.productovariante'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.tipoinsumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.unidadmedida'),
        ),
        migrations.AddField(
            model_name='usoinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='bodega.insumo'),
        ),
        migrations.AddField(
            model_name='usoinsumo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_usados', to='Producto.productovariante'),
        ),
        migrations.AddField(
            model_name='usoinsumo',
            name='user_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
    ]
