# Generated by Django 5.1.6 on 2025-03-15 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
        ('bodega', '0002_initial'),
        ('empresas', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos_insumo',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='ingresos_producto',
            name='ProductoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='ingresos_producto',
            name='ProveedorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='ingresos_producto',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='ingresos_insumo',
            name='InsumoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.insumo'),
        ),
        migrations.AddField(
            model_name='salidas_producto',
            name='LocalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.inventariolocal'),
        ),
        migrations.AddField(
            model_name='salidas_producto',
            name='ProductoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='salidas_producto',
            name='ProveedorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='salidas_producto',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='Tipo_insumoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.tipo_insumo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='Unidad_MedidaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.unidad_medida'),
        ),
        migrations.AddField(
            model_name='uso_insumo',
            name='InsumoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.insumo'),
        ),
        migrations.AddField(
            model_name='uso_insumo',
            name='ProductoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='uso_insumo',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
    ]
