# Generated by Django 5.1.7 on 2025-03-22 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='bodega.stock'),
        ),
    ]
