# Generated by Django 5.1.7 on 2025-03-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_alter_salidaproducto_producto'),
        ('locales', '0002_local_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaproducto',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.local'),
        ),
    ]
