# Generated by Django 5.1.7 on 2025-03-28 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_alter_salidaproducto_local'),
        ('locales', '0002_local_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionrecepcion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salidaproducto',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.inventariolocal'),
        ),
    ]
