# Generated by Django 5.1.7 on 2025-03-29 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_entregacorte_cantidad_lavado_and_more'),
        ('locales', '0002_local_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaproducto',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales.inventariolocal'),
        ),
    ]
