# Generated by Django 5.1.7 on 2025-03-29 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0008_alter_salidaproducto_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='salida',
            field=models.OneToOneField(default=1, limit_choices_to={'es_lavado': True}, on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='bodega.salidaproducto'),
            preserve_default=False,
        ),
    ]
