# Generated by Django 5.1.7 on 2025-03-29 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0009_remove_entradaproducto_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproducto',
            name='cantidad',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='salida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='bodega.salidaproducto'),
        ),
    ]
