# Generated by Django 5.1.7 on 2025-04-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_alter_salidaproducto_local'),
        ('bodega', '0011_alter_usoinsumo_uso_destino'),
    ]

    operations = [
    ]
