# Generated by Django 5.1.7 on 2025-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0015_alter_salidaproducto_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregacorte',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
