# Generated by Django 5.1.7 on 2025-07-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0016_alter_entregacorte_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregacorte',
            name='salida_lavado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrega_lavado', to='bodega.salidaproducto'),
        ),
    ]
