# Generated by Django 5.1.7 on 2025-07-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0017_entregacorte_salida_lavado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleIngresoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.ingresoinsumo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.insumo')),
            ],
        ),
    ]
