# Generated by Django 5.1.7 on 2025-07-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0018_detalleingresoinsumo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleIngresoInsumo',
        ),
    ]
