# Generated by Django 5.1.7 on 2025-07-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0020_detalleingresoinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_inicial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
