# Generated by Django 5.1.7 on 2025-07-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0021_insumo_stock_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='stock_inicial',
            new_name='stock_actual',
        ),
    ]
