# Generated by Django 5.1.7 on 2025-07-18 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0022_rename_stock_inicial_insumo_stock_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleingresoinsumo',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.ingresoinsumo'),
        ),
    ]
