# Generated by Django 5.1.7 on 2025-07-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0023_alter_detalleingresoinsumo_ingreso'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caducidad', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.ingresoinsumo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Uso', 'Uso'), ('Ajuste', 'Ajuste')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.insumo')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfilusuario')),
            ],
        ),
    ]
