# Generated by Django 5.1.7 on 2025-04-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0002_alter_diseno_options'),
        ('proveedores', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolloTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rollo', models.CharField(max_length=50, unique=True)),
                ('referencia', models.CharField(max_length=100)),
                ('numero_referencia', models.CharField(max_length=50, unique=True)),
                ('metros_solicitados', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largo_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('largo_restante', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kilos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto'), ('Agotado', 'Agotado')], default='Completo', max_length=50)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_unidades', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('cortador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_produccion', to='usuarios.perfilusuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencia_producto', to='Producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CorteTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_corte', models.CharField(max_length=50, unique=True)),
                ('largo_utilizado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capas_cortadas', models.PositiveIntegerField()),
                ('metros_tendidos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medida_tendido_mesa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('colas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('metros_dft_gastados', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rendimiento_rollo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_corte', models.DateField()),
                ('categoria', models.CharField(choices=[('Adulto', 'Adulto'), ('Niño', 'Niño')], default='Adulto', max_length=10)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes', to='trazabilidad.ordenproduccion')),
                ('rollo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.rollotela')),
            ],
        ),
        migrations.CreateModel(
            name='TallaCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('4', '4'), ('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=2)),
                ('cantidad', models.PositiveIntegerField()),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallas_cortes', to='trazabilidad.cortetela')),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='rollotela',
            name='tela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.tela'),
        ),
    ]
