# Generated by Django 5.1.7 on 2025-04-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenproduccion',
            options={'verbose_name': 'Orden Producción', 'verbose_name_plural': 'Ordenes Producción'},
        ),
        migrations.RemoveField(
            model_name='tela',
            name='ancho',
        ),
    ]
