# Generated by Django 5.1.7 on 2025-04-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0002_alter_ordenproduccion_options_remove_tela_ancho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollotela',
            name='fecha_registro',
            field=models.DateTimeField(),
        ),
    ]
