# Generated by Django 5.1.7 on 2025-04-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0003_alter_rollotela_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollotela',
            name='kilos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rollotela',
            name='largo_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rollotela',
            name='largo_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='rollotela',
            name='metros_solicitados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
