# Generated by Django 5.1.7 on 2025-04-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0004_alter_rollotela_kilos_alter_rollotela_largo_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollotela',
            name='largo_restante',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
