# Generated by Django 5.1.7 on 2025-04-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0005_alter_rollotela_largo_restante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tela',
            name='color',
        ),
        migrations.AddField(
            model_name='rollotela',
            name='color',
            field=models.CharField(default='amarill', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rollotela',
            name='numero_rollo',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rollotela',
            name='referencia',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
