# Generated by Django 5.1.7 on 2025-04-17 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0006_remove_tela_color_rollotela_color_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetazoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capas_cortadas', models.PositiveIntegerField()),
                ('metros_tendidos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medida_tendido_mesa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('faltante', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_registro', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.ordenproduccion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfilusuario')),
                ('rollo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trazabilidad.rollotela')),
            ],
            options={
                'verbose_name': 'Retazo de Tela',
                'verbose_name_plural': 'Retazos de Tela',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
