# Generated by Django 5.1.7 on 2025-03-22 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], default='Ingreso', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('monto', models.FloatField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('factura_remision', models.CharField(blank=True, max_length=50, null=True)),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.categoriamercaderia')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('monto', models.FloatField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('documento', models.PositiveIntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('anio', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.categoriamercaderia')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('saldo_mensual', models.FloatField()),
                ('saldo_acumulado', models.FloatField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.cuenta')),
            ],
        ),
    ]
