# Generated by Django 5.1.6 on 2025-03-15 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compras', '0002_initial'),
        ('Cuentas', '0001_initial'),
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='gastos_operativos',
            name='Aprobador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Autorizador', to='usuarios.perfilusuario'),
        ),
        migrations.AddField(
            model_name='gastos_operativos',
            name='EmpresaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='gastos_operativos',
            name='Factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.facturacompra'),
        ),
        migrations.AddField(
            model_name='gastos_operativos',
            name='UserResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solicitante', to='usuarios.perfilusuario'),
        ),
    ]
