# Generated by Django 5.1.6 on 2025-03-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razon_Social', models.CharField(max_length=100)),
                ('Tipo_documento', models.CharField(choices=[('C.C.', 'C.C'), ('NIT.', 'NIT.'), ('PAS', 'PAS')], default='NIT', max_length=50)),
                ('Identificacion', models.IntegerField(unique=True)),
                ('Telefono', models.IntegerField()),
                ('Correo', models.EmailField(max_length=100, unique=True)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Fecha_Inicio_Actividad', models.DateField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
