# Generated by Django 5.2.4 on 2025-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula Ciudadania'), ('NIT.', 'NNúmero Identificación TributariaIT.'), ('PAS', 'Pasaporte')], default='NIT', max_length=50),
        ),
    ]
