# Generated by Django 5.1.6 on 2025-03-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariolocal',
            old_name='qty_minimo',
            new_name='stock_minimo',
        ),
    ]
