# Generated by Django 5.1.6 on 2025-03-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_rename_qty_minimo_inventariolocal_stock_minimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariolocal',
            options={'verbose_name': 'Inventario Local', 'verbose_name_plural': 'Inventario Local'},
        ),
    ]
