# Generated by Django 5.1.6 on 2025-03-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_rename_cantidad_disponible_inventariolocal_entradas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa_relacionada', to='empresas.empresa'),
        ),
    ]
