# Generated by Django 5.1.7 on 2025-03-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_ventas_localid'),
        ('bodega', '0004_alter_salidas_producto_localid'),
        ('empresas', '0006_remove_local_horario_habil_and_more'),
        ('nomina', '0004_alter_contrato_local'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventarioLocal',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
    ]
